apiVersion: opentelemetry.io/v1alpha1
kind: OpenTelemetryCollector
metadata:
  name: otel-sidecar
spec:
  mode: sidecar
  hostNetwork: true
  image: otel/opentelemetry-collector-contrib:0.46.0
  config: |
    receivers:
      otlp:
        protocols:
          grpc:
          http:
    processors:
      batch:
        send_batch_max_size: 1000
        send_batch_size : 800
        timeout: 30s
    exporters:
      logging:
      otlp:
        endpoint: "http://oteld-collector.default.svc.cluster.local:4317"
        tls:
          insecure: true
      dynatrace:
        # optional - Dimensions specified here will be included as a dimension on every exported metric
        #            unless that metric already has a dimension with the same key.
        # optional - prefix will be prepended to each metric name in prefix.name format
        prefix: otpsidecar
        endpoint: "TENANTURL_TOREPLACE/api/v2/metrics/ingest"
        # Token must at least have the Ingest metrics (metrics.ingest) permission
        api_token: "DT_API_TOKEN_TO_REPLACE"
    service:
      pipelines:
        traces:
          receivers: [otlp]
          processors: []
          exporters: [logging,otlp]
        metrics:
          receivers: [otlp]
          processors: [batch]
          exporters: [logging,dynatrace]